### ISSUE TITLE
maas-anvil prompts for a VIP even if there's an empty `virtual_ip` in the manifest

### ISSUE THREAD

**Issue by bjornt** [canonical/maas-anvil#58]
In order to deploy things automatically, I provide this manifest to maas-anvil:

```
deployment:
  bootstrap:
    management_cidr: 10.5.120.0/24
  haproxy:
    virtual_ip:
  postgres:
    max_connections: 300
  software: {}
```

However, maas-anvil still stops and prompts me for the VIP and I need to press enter to indicate I don't want a VIP.

There should be a way to use the manifest to tell maas-anvil that no VIP is to be used.
