### ISSUE TITLE
Adding a VIP via a manifest after bootstrap does nothing

### ISSUE THREAD

**Issue by jeff-hillman** [canonical/maas-anvil#84]
Performing a clean installation following the GH README and using `--accept-defaults` creates a clean installation.  2 nodes were subsequently added without issue.

Accepting defaults, however, doesn't deploy keepalived

Later, a manifest consisting of:

```
deployment:
  bootstrap:
    # Management networks shared by hosts (CIDRs, separated by comma)
    management_cidr: "192.168.1.0/24"
  postgres:
    # Maximum number of concurrent connections to allow to the database server
    max_connections: "default"
  haproxy:
    # Virtual IP to use for the Cluster in HA
    virtual_ip: "192.168.1.11"
    # Path to SSL Certificate for HAProxy
    ssl_cert: ""
    # Path to private key for the SSL certificate
    ssl_key: ""
    # Path to CA cert chain, for use with self-signed SSL certificates (enter nothing to skip)
    ssl_cacert: ""
    # TLS mode: ['termination', 'passthrough', 'disabled']
    tls_mode: "disabled"
  maas-region:
    # Path to SSL Certificate for HAProxy
    ssl_cert: ""
    # Path to private key for the SSL certificate
    ssl_key: ""
    # Path to CA cert chain, for use with self-signed SSL certificates (enter nothing to skip)
    ssl_cacert: ""
    # TLS mode: ['passthrough', 'disabled']
    tls_mode: "disabled"
software:
  # juju:
  #   bootstrap_args: []
  #   scale_args: []
  # charms:
  #   maas-region:
  #     channel: 3.5/edge
  #     revision: null
  #     config: null
  #   maas-agent:
  #     channel: 3.5/edge
  #     revision: null
  #     config: null
  #   haproxy:
  #     channel: latest/stable
  #     revision: null
  #     config: null
  #   postgresql:
  #     channel: 14/stable
  #     revision: null
  #     config: null
  #   keepalived:
  #     channel: latest/stable
  #     revision: null
  #     config: null
  # terraform:
  #   maas-region-plan:
  #     source: /snap/maas-anvil/78/etc/deploy-maas-region
  #   maas-agent-plan:
  #     source: /snap/maas-anvil/78/etc/deploy-maas-agent
  #   haproxy-plan:
  #     source: /snap/maas-anvil/78/etc/deploy-haproxy
  #   postgresql-plan:
  #     source: /snap/maas-anvil/78/etc/deploy-postgresql
```

Is applied, notice the "virtual_ip" setting.  The manifest is applied with `maas-anvil refresh --manifest <file>`

running `maas-anvil manfiest list` has the new manifest listed.  and a `maas-anvil manifest show` has the "virtual_ip" configuration, however, keepalived is NOT installed and the VIP isn't applied anywhere.

running `maas-anvil manifest generate` creates a new file that does NOT have th VIP listed in it.
