### ISSUE TITLE
Having VIP set during bootstrap causes maas-region to hang

### ISSUE THREAD

**Issue by jeff-hillman** [canonical/maas-anvil#85]
Performing a bootstrap with either ommitting `--accept-defaults` or aplying a manifest file with a VIP configured, causes the maas-region/0 unit to hang with the message:

```
maas-region/0*   waiting   idle   0        192.168.1.220   53,3128,5239-5247,5250-5274,5280-5284,5443,8000/tcp 53,67,69,123,323,5241-5247/udp  Waiting for dat
abase DSN
```

During the bootstrap without `--accpt-defaults` the following settings are configured:

* accepting the cidr network
* set max connections to 250
* saying disabled for the TLS cert
* setting a VIP on my network (which is pingable when haproxy/keepalived comes up

It seems in any case where a VIP is presetn during bootstrap that MAS region is having some form of issue.

Manifest used is:

```
deployment:
  bootstrap:
    # Management networks shared by hosts (CIDRs, separated by comma)
    management_cidr: "192.168.1.0/24"
  postgres:
    # Maximum number of concurrent connections to allow to the database server
    max_connections: "default"
  haproxy:
    # Virtual IP to use for the Cluster in HA
    virtual_ip: "192.168.1.11"
    # Path to SSL Certificate for HAProxy
    ssl_cert: ""
    # Path to private key for the SSL certificate
    ssl_key: ""
    # Path to CA cert chain, for use with self-signed SSL certificates (enter nothing to skip)
    ssl_cacert: ""
    # TLS mode: ['termination', 'passthrough', 'disabled']
    tls_mode: "disabled"
  maas-region:
    # Path to SSL Certificate for HAProxy
    ssl_cert: ""
    # Path to private key for the SSL certificate
    ssl_key: ""
    # Path to CA cert chain, for use with self-signed SSL certificates (enter nothing to skip)
    ssl_cacert: ""
    # TLS mode: ['passthrough', 'disabled']
    tls_mode: "disabled"
software:
  # juju:
  #   bootstrap_args: []
  #   scale_args: []
  # charms:
  #   maas-region:
  #     channel: 3.5/edge
  #     revision: null
  #     config: null
  #   maas-agent:
  #     channel: 3.5/edge
  #     revision: null
  #     config: null
  #   haproxy:
  #     channel: latest/stable
  #     revision: null
  #     config: null
  #   postgresql:
  #     channel: 14/stable
  #     revision: null
  #     config: null
  #   keepalived:
  #     channel: latest/stable
  #     revision: null
  #     config: null
  # terraform:
  #   maas-region-plan:
  #     source: /snap/maas-anvil/78/etc/deploy-maas-region
  #   maas-agent-plan:
  #     source: /snap/maas-anvil/78/etc/deploy-maas-agent
  #   haproxy-plan:
  #     source: /snap/maas-anvil/78/etc/deploy-haproxy
  #   postgresql-plan:
  #     source: /snap/maas-anvil/78/etc/deploy-postgresql
```
